artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/DeependraVerma/Data-for-Projects/raw/main/foodtimepredictor.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/finalTrain.csv
  validated_data_path: artifacts/data_validation/finalTrain.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/finalTrain.csv
  transformed_train_path: artifacts/data_transformation/processed_train.csv
  transformed_test_path: artifacts/data_transformation/processed_test.csv
  preprocessed_obj_path: artifacts/data_transformation/preprocessor.pkl
  feature_engg_obj_path: artifacts/data_transformation/feature_engg_obj.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/processed_train.csv
  test_data_path: artifacts/data_transformation/processed_test.csv
  model_name: model.joblib
  n_estimators: 100
  min_samples_split: 2
  target_column: Time_taken (min)

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json